# Generated by Django 4.2 on 2023-04-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('content', models.TextField(verbose_name='Post Body')),
                ('author', models.CharField(max_length=225)),
                ('date_published', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
